### ISSUE TITLE
#22 merged with unresolved reviews: changes requested

### ISSUE THREAD

**Issue by ethanwu10** [climatEDU/climatEDU#35]
#22 merge by @kmh11 

Changes requested by @ethanwu10 (deduplicated):
https://github.com/climatEDU/climatEDU/pull/22#discussion_r485224978
https://github.com/climatEDU/climatEDU/pull/22#discussion_r485227679
https://github.com/climatEDU/climatEDU/pull/22#discussion_r485227796
https://github.com/climatEDU/climatEDU/pull/22#discussion_r485228624
https://github.com/climatEDU/climatEDU/pull/22#discussion_r485228997
https://github.com/climatEDU/climatEDU/pull/22#discussion_r485229614

**Comment by kmh11** [comment]
everything but input size has been fixed
